version: '3'

services:
  streamlit_app_1:
    image: stest
    environment:
        - PORT=8501
        - ENV_TYPE=dev
    networks:
      - backend

  streamlit_app_2:
    image: stest
    environment:
      - PORT=8502
      - ENV_TYPE=dev
    networks:
      - backend

  streamlit_app_3:
    image: stest
    environment:
      - PORT=8503
      - ENV_TYPE=dev
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - streamlit_app_1
      - streamlit_app_2
      - streamlit_app_3

networks:
  backend:
